version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: swish_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: swish_user
      POSTGRES_PASSWORD: swish_password
      POSTGRES_DB: swish_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
